<!-- <package format="2">
  <name>hands_on_intervention</name>
  <version>2.0.0</version>
  <description>
     hands_on_intervention package for IFROS
  </description>
  <author></author>
  <maintainer email="test@test.com">Roger Pi</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>


  <depend>rospy</depend>
</package> -->
<package format="2">
  <name>hands_on_intervention</name>
  <version>0.0.1</version>
  <description>Your package description</description>

  <maintainer email="your_email@example.com">Your Name</maintainer>
  <license>BSD</license>

  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>message_generation</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  

  <export>
  </export>
</package>
